# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'slidecrea.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(341, 243)
        MainWindow.setMinimumSize(QtCore.QSize(310, 208))
        MainWindow.setMaximumSize(QtCore.QSize(341, 243))
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.lineEditImagesPath = QtWidgets.QLineEdit(self.page)
        self.lineEditImagesPath.setEnabled(False)
        self.lineEditImagesPath.setObjectName("lineEditImagesPath")
        self.verticalLayout_2.addWidget(self.lineEditImagesPath)
        self.selectImagesPathButton = QtWidgets.QPushButton(self.page)
        self.selectImagesPathButton.setObjectName("selectImagesPathButton")
        self.verticalLayout_2.addWidget(self.selectImagesPathButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.createXMLImagesFileButton = QtWidgets.QPushButton(self.page)
        self.createXMLImagesFileButton.setObjectName("createXMLImagesFileButton")
        self.verticalLayout_2.addWidget(self.createXMLImagesFileButton)
        self.progressBarIImagesXML = QtWidgets.QProgressBar(self.page)
        self.progressBarIImagesXML.setProperty("value", 0)
        self.progressBarIImagesXML.setObjectName("progressBarIImagesXML")
        self.verticalLayout_2.addWidget(self.progressBarIImagesXML)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SlideCrea"))
        self.label.setText(_translate("MainWindow", "Just Slideshow"))
        self.selectImagesPathButton.setText(_translate("MainWindow", "Select Images Path"))
        self.createXMLImagesFileButton.setText(_translate("MainWindow", "Create XML File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
